version: '3.8'

services:
  app:
    build: .
    ports:
      - "6010:6010"
    environment:
      - NODE_ENV=production
      - PORT=6010
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-site_ai_server}
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - siteai-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME:-site_ai_server}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - siteai-network

volumes:
  mysql_data:

networks:
  siteai-network:
    driver: bridge
